[project]
name = "libtagarray"
requires-python = ">=3.11"
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python"
]

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"
