name: CI

on:
  push:
  pull_request:
    branches: [ "master" ]

jobs:
  GCC-build:
    runs-on: ${{ matrix.image }}

    strategy:
      matrix:
        image: [ 'ubuntu-20.04' ]
        GCC: [ '9', '11' ]
        BUILD_TYPE: [ 'Release' ]
        include:
          - image: 'ubuntu-latest'
            GCC: '12'
            BUILD_TYPE: 'Debug'

    steps:
    - uses: actions/checkout@v4
    - uses: lukka/get-cmake@latest
      with:
        cmakeVersion: "~3.25.0"

    - name: Install GCC
      run: sudo apt update && sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt install g++-${{ matrix.GCC }} gfortran-${{ matrix.GCC }}

    - name: Configure CMake
      run: cmake -G"Ninja" -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ matrix.BUILD_TYPE }} -DENABLE_FORTRAN=ON -DENABLE_TESTING=ON -DCMAKE_CXX_COMPILER=g++-${{ matrix.GCC }} -DCMAKE_Fortran_COMPILER=gfortran-${{ matrix.GCC }} -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest . --output-on-failure

    - name: Install
      run: cmake --build ${{github.workspace}}/build --target install
